assets/urls.py
from django.urls import path
from . import views


app_name = "assets"
urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    
    path("", views.AssetList.as_view(), name="home"),
    path("featured/", views.featured_set, name='featured'),
    path("asset/<int:pk>", views.AssetDetail.as_view(), name="AssetDetail"),
]

devloot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('assets.urls')),
]

assets/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    ROLE_CHOICES = [
        ('user', 'User'),
        ('contributor', 'Contributor'),
        ('moderator', 'Moderator'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=150)
    role = models.CharField(max_length=25, choices=ROLE_CHOICES, default='user', null=True)
    payment_email = models.EmailField(max_length=150, null=True)
    contributor_link = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Tag(models.Model):
    name = models.CharField(max_length=30, null=True)
    description = models.TextField(max_length=600, blank=True)

    def __str__(self):
        return f"Tag: {self.name}"


class Asset(models.Model):
    TYPE_CHOICES = [
        ('3d', '3D'),
        ('2d', '2D'),
        ('addons', 'Add-on'),
        ('rigged_models', 'Rigged Models'),
        ('essentials', 'Essentials'),
        ('gui', 'GUI'),
        ('templates', 'Templates'),
        ('audio', 'Audio'),
        ('tools', 'Tools'),
        ('vfx', 'VFX'),
    ]
    name = models.CharField(max_length=200, null=True)
    description = models.TextField(max_length=800, null=True)
    asset_type = models.CharField(max_length=25, choices=TYPE_CHOICES, null=True)
    creation_date = models.DateTimeField(auto_now_add=True, null=True)
    moved_to_general = models.DateTimeField(null=True, blank=True)
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ('-creation_date', 'name')

    def __str__(self):
        return f"Asset: {self.name} - {self.id}"


class FeaturedSet(models.Model):
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('expired', 'Expired'),
        ('ready', 'Ready'),
        ('building', 'Building'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, null=True)
    name = models.CharField(max_length=150, null=True)
    description = models.TextField(max_length=700, null=True)
    active_date = models.DateTimeField(null=True, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True, null=True)
    assets = models.ManyToManyField(Asset)

    class Meta:
        ordering = ('-creation_date', 'status')
    
    def __str__(self):
        return f"FeaturedSet: {self.creation_date} - {self.id}"

assets/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({'class': 'shadow border rounded w-full py-2 px-3 text-gray-800 mb-3'})
        self.fields['password2'].widget.attrs.update({'class': 'shadow border rounded w-full py-2 px-3 text-gray-800 mb-3'})

    email = forms.EmailField(max_length=150)
    username = forms.CharField(max_length=30)

    email.widget.attrs.update({'class': 'shadow border rounded w-full py-2 px-3 text-gray-800 mb-2'})
    username.widget.attrs.update({'class': 'shadow border rounded w-full py-2 px-3 text-gray-800 mb-2'})

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

assets/views.py
from django.shortcuts import render, redirect
from .models import Asset, FeaturedSet
from django.views.generic import ListView, DetailView
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages

from .forms import CreateUserForm


# Create your views here.
class AssetList(ListView):
    paginate_by = 10
    model = Asset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['featured_set'] = FeaturedSet.objects.filter(status='active').first()
        return context


class AssetDetail(DetailView):
    model = Asset


def registerPage(request):
    form = CreateUserForm(request.POST)
    if form.is_valid():
        user = form.save()
        user.refresh_from_db()
        user.profile.email = form.cleaned_data.get('email')
        user.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(request, user)
        messages.success(request, 'User Created')
        return redirect('assets:home')
    else:
        form = CreateUserForm()
    return render(request, 'assets/register.html', {'form': form})


def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('assets:home')
        else:
            messages.info(request, 'Username / password combo incorrect')
    
    return render(request, 'assets/login.html')


def logoutPage(request):
    logout(request)
    return redirect('assets:home')


def featured_set(request):
    current_feature = FeaturedSet.objects.filter(status='active').first()

    return render(request, 'assets/featured_set.html', {'current_feature': current_feature})

assets/templates/assets/asset_detail.html
{% extends 'main.html' %}


{% block title %}
    {{ object.name }} - {{ block.super }}
{% endblock %}
    

{% block content %}
    <div class="container mx-auto px-6 lg:px-8 mt-8">
        <div class="w-full flex flex-wrap">
            <h2 class="text-xl font-semibold tracking-widest text-accent-yellow mb-1 uppercase truncate w-full">{{ object.name }}</h2>
            <h3 class="mb-4 italic text-gray-500 w-full">Contributor Name Here</h3>
        </div>
    </div>
    <div class="container mx-auto px-4">
        <div class="w-full mt-3 flex flex-wrap justify-between items-center lg:items-start">
            <img class="rounded w-full h-auto px-2 lg:w-2/3"
                src="https://via.placeholder.com/600x360/ffd437/000000?text=Individual+Item" alt="Item text">
            <div class="w-full flex justify-between mt-2 px-1 lg:w-1/3 lg:flex-wrap lg:-mt-1">
                <div class="w-1/4 p-1 lg:w-1/2">
                    <img class="rounded" src="https://via.placeholder.com/600x360/ffd437/000000?text=Individual+Item"
                        alt="Item text">
                </div>
                <div class="w-1/4 p-1 lg:w-1/2">
                    <img class="rounded" src="https://via.placeholder.com/600x360/ffd437/000000?text=Individual+Item"
                        alt="Item text">
                </div>
                <div class="w-1/4 p-1 lg:w-1/2">
                    <img class="rounded" src="https://via.placeholder.com/600x360/ffd437/000000?text=Individual+Item"
                        alt="Item text">
                </div>
                <div class="w-1/4 p-1 lg:w-1/2">
                    <img class="rounded" src="https://via.placeholder.com/600x360/ffd437/000000?text=Individual+Item"
                        alt="Item text">
                </div>
            </div>
            <div class="flex w-full px-2 my-4">

                <button
                    class="w-1/2 border-gray-200 border rounded p-2 mr-2 hover:bg-gray-200 hover:text-gray-800"><i
                        class="fas fa-heart"></i></button>
                <button
                    class="w-1/2 border-gray-200 border rounded p-2 ml-2 hover:bg-gray-200 hover:text-gray-800"><i
                        class="fas fa-download"></i></button>
            </div>
        </div>
    </div>
    <div class="container mx-auto px-6">
        <div class="w-full">
            <h3 class="text-xl tracking-wider text-accent-yellow mt-3">Description</h3>
            <div class="text-gray-400 max-w-screen-md">
                {{ object.description }}
            </div>
        </div>
        <div class="w-full flex flex-wrap">
            <h3 class="w-full text-xl tracking-wider text-accent-yellow mt-3 mb-1">Related Tags</h3>
            {% for tag in object.tags.all %}
                <button
                    class="p-1 m-2 border-gray-200 border tracking-wide rounded hover:bg-gray-200 hover:text-gray-800">{{tag.name}}</button>

            {% empty %}
                <span>No tags associated with this asset</span>
            {% endfor %}
        </div>

    </div>
{% endblock %}

assets/templates/assets/asset_list.html
{% extends 'main.html' %}

{% block content %}
    <div class="container mx-auto mt-4 flex px-2 md:px-4 lg:px-6">
        <div class="w-full md:w-2/3 md:pr-2 flex flex-wrap xl:w-3/4">
            <div class="w-full mt-2 px-2 xl:w-2/3">
                <a href="{% url 'assets:featured' %}"><img class="" src="https://via.placeholder.com/1200x800/3d70ff/FFFFFF?text=Featured+Section" alt=""></a>
            </div>
            <div class="w-1/2 mt-4 px-2 xl:hidden">
                <a href="{% url 'assets:featured' %}"><img class="" src="https://via.placeholder.com/1200x800/3d70ff/FFFFFF?text=Search+Section" alt=""></a>
            </div>
            <div class="w-1/2 mt-4 px-2 xl:hidden">
                <img class="" src="https://via.placeholder.com/1200x800/3d70ff/FFFFFF?text=Featured+Section" alt="">
            </div>
            <div class="hidden xl:flex xl:flex-col xl:w-1/3 xl:mt-2 xl:h-auto justify-between">
                <div class="w-full px-2">
                    <img class="" src="https://via.placeholder.com/1200x800/3d70ff/FFFFFF?text=Featured+Section" alt="">
                </div>
                <div class="w-full px-2">
                    <img class="" src="https://via.placeholder.com/1200x800/3d70ff/FFFFFF?text=Featured+Section" alt="">
                </div>
            </div>
        </div>
        <div class="hidden md:block md:w-1/3 md:pl-3 text-white xl:w-1/4">
            <div class="border-b border-opacity-25 border-white pb-2 md:flex md:justify-between md:items-start">
                <h3 class="inline text-lg">Filter by</h3>
                <a class="text-accent-yellow" href="#"><span>clear filters</span></a>
            </div>
            <div class="w-full flex-col mt-3">
                <div class="w-full flex items-center mt-2">
                    <button class="h-4 w-4 border rounded border-gray-300 mr-2"></button>
                    <div class="h-6 text-gray-100">Asset Type</div>
                </div>
                <div class="w-full flex items-center mt-2">
                    <button class="h-4 w-4 border rounded border-gray-300 mr-2"></button>
                    <div class="h-6 text-gray-100">Asset Type</div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mx-auto px-6 lg:px-8 mt-8">
        <h2 class="text-xl font-semibold tracking-widest text-gray-200 uppercase mb-2">Popular</h2>
    </div>
    <div class="container px-4 mx-auto lg:px-6 flex flex-wrap">
        {% for asset in object_list %}
            <div class="w-1/2 h-auto rounded-lg overflow-hidden px-1 md:px-2 text-gray-400 pb-3 mb-4 lg:w-1/3 xl:w-1/4">
                <img src="https://via.placeholder.com/500x300/ffd437/000000?text=Individual+Item" alt="Item text">
                <h3 class="text-gray-600 text-xs uppercase tracking-wide font-semibold mt-3">Contributor Name</h3>
                <h2 class="text-gray-100 truncate text-lg font-semibold"><a href="{% url 'assets:AssetDetail' pk=asset.id %}">{{asset.name}}</a></h2>
                <div class="mt-2 flex justify-between items-center">
                    <div class="w-2/3">
                        <span class="text-gray-500 text-xs italic font-light">{% for tag in asset.tags.all %}{{tag.name}} | {% empty %}No Tags{% endfor %}</span>
                    </div>
                    <div class="w-1/3 pr-2 text-right">
                            <a href=""><i class="fas fa-heart fa-lead mx-2" aria-hidden="true"></i></a>
                    </div>
                </div>
            </div>
        {% empty %}
            Oh no, empty!
        {% endfor %}
        {% if is_paginated %}
        <nav >
            <ul class="pagination" >
                <li class="page-item" >
                <a
                    href="{% url 'assets:home' %}?page=1"
                    class="page-link"
                >
                    First
                </a >
                </li >
                {% if page_obj.has_previous %}
                <li class="page-item" >
                    <a
                    href="{% url 'assets:home' %}?page={{ page_obj.previous_page_number }}"
                    class="page-link"
                    >
                    {{ page_obj.previous_page_number }}
                    </a >
                </li >
                {% endif %}
                <li class="page-item active" >
                <a
                    href="{% url 'assets:home' %}?page={{ page_obj.number }}"
                    class="page-link"
                >
                    {{ page_obj.number }}
                </a >
                </li >
                {% if page_obj.has_next %}
                <li class="page-item" >
                    <a
                    href="{% url 'assets:home' %}?page={{ page_obj.next_page_number }}"
                    class="page-link"
                    >
                    {{ page_obj.next_page_number }}
                    </a >
                </li >
                {% endif %}
                <li class="page-item" >
                <a
                    href="{% url 'assets:home' %}?page=last"
                    class="page-link"
                >
                    Last
                </a >
                </li >
            </ul >
        </nav >
  {% endif %}
    </div>
{% endblock %}

assets/templates/assets/featured_set.html
{% extends 'main.html' %}


{% block title %}
    {{ current_feature.name }} - {{ block.super }}
{% endblock %}
    

{% block content %}
    <div class="w-full bg-accent-green pt-12 pb-10">
        <div class="container mx-auto px-4 lg:px-8 lg:flex lg:items-center">
            <div class="lg:w-2/3 lg:pr-12 xl:pr-32">
                <h2 class="text-3xl text-white font-bold">{{ current_feature.name }}</h2>
                <p class="text-white text-lg tracking-wide lg:tracking-normal leading-snug xl:leading-normal">
                    {{ current_feature.description }}
                </p>
            </div>
            <button
                class="lg:hidden rounded p-2 text-gray-800 font-bold border mt-6 border-opacity-50 shadow hover:bg-opacity-75 border-nav-bg bg-accent-yellow">Donate
                to the Makers</button>
            <div class="hidden lg:w-1/3 lg:block bg-white rounded p-3">
                <h2 class="text-xl font-semibold leading-tight tracking-widest text-gray-900 uppercase text-center">
                    Support the Contributors</h2>
                <div class="flex flex-wrap w-full mx-auto justify-center h-auto">
                    <button
                        class="xl:w-3/4 rounded bg-accent-yellow border border-gray-800 border-opacity-75 text-gray-800 font-semibold uppercase p-2 w-full mt-3 mb-3 hover:bg-opacity-75">For
                        the cause!</button>
                </div>
                <p class="text-gray-800 italic max-w-xl text-center mx-auto text-sm">
                    Our contributors share their assets without expectation of return, but contributing can help makers dedicate more time to their assets.
                </p>
            </div>
        </div>
    </div>
    <div class="container mx-auto px-6 lg:px-8 mt-8">
        <h2 class="text-xl font-semibold tracking-widest text-gray-200 uppercase mb-2">Included in this pack</h2>
    </div>
    <div class="container px-4 mx-auto lg:px-6 flex flex-wrap">
        {% for asset in current_feature.assets.all %}
            <div class="w-1/2 h-auto rounded-lg overflow-hidden px-1 md:px-2 text-gray-400 pb-3 mb-4 lg:w-1/3 xl:w-1/4">
                <img src="https://via.placeholder.com/500x300/ffd437/000000?text=Individual+Item" alt="Item text">
                <h3 class="text-gray-600 text-xs uppercase tracking-wide font-semibold mt-3">Contributor Name</h3>
                <h2 class="text-gray-100 truncate text-lg font-semibold"><a href="{% url 'assets:AssetDetail' pk=asset.id %}">{{asset.name}}</a></h2>
                <div class="mt-2 flex justify-between items-center">
                    <div class="w-2/3">
                        <span class="text-gray-500 text-xs italic font-light">{% for tag in asset.tags.all %}{{tag.name}} | {% empty %}No Tags{% endfor %}</span>
                    </div>
                    <div class="w-1/3 pr-2 text-right">
                            <a href=""><i class="fas fa-heart fa-lead mx-2" aria-hidden="true"></i></a>
                    </div>
                </div>
            </div>
        {% empty %}
            Oh no, empty!
        {% endfor %}
    </div>
    <div class="container mx-auto px-6 lg:px-8 mt-8">
        <h2 class="text-xl font-semibold leading-3 tracking-widest text-gray-200 uppercase text-center">Support the
            Contributors</h2>
        <div class="flex flex-wrap w-full lg:w-1/2 mx-auto justify-center h-auto">
            <button
                class="w-1/5 rounded p-2 mx-2 mb-3 text-gray-200 font-bold border mt-6 bg-card-bg border-opacity-75 shadow border-accent-yellow hover:bg-gray-300 hover:text-gray-800">$5</button>
            <button
                class="w-1/5 rounded p-2 mx-2 mb-3 text-gray-200 font-bold border mt-6 bg-card-bg border-opacity-75 shadow border-accent-yellow hover:bg-gray-300 hover:text-gray-800">$10</button>
            <button
                class="w-1/5 rounded p-2 mx-2 mb-3 text-gray-200 font-bold border mt-6 bg-card-bg border-opacity-75 shadow border-accent-yellow hover:bg-gray-300 hover:text-gray-800">$25</button>
            <button
                class="w-1/5 rounded p-2 mx-2 mb-3 text-gray-200 font-bold border mt-6 bg-card-bg border-opacity-75 shadow border-accent-yellow hover:bg-gray-300 hover:text-gray-800">$50</button>
            <button
                class="lg:w-1/2 rounded bg-accent-yellow border border-gray-800 border-opacity-75 text-gray-800 font-semibold uppercase p-2 w-full mt-3 mb-3 hover:bg-white hover:bg-opacity-75">For
                the cause!</button>
        </div>
        <p class="text-gray-300 italic max-w-xl text-center mx-auto font-semibold">
            These assets took a lot of love and effort to make. Our contributors share their assets without expectation
            of return, but contributing can help makers dedicate more time to their assets.
        </p>
        <p class="text-gray-600 text-sm italic max-w-xl text-center mx-auto mt-2">
            No less than 80% of your contribution goes directly to the contributors. ProjectName takes a small portion
            to cover the cost of user downloads and development time.
        </p>
    </div>
{% endblock %}

assets/templates/assets/home.html
{% extends 'assets/main.html' %}

{% block content %}
    {% for asset in assets %}
        <div class="container mx-auto">
            <h2>{{asset.name}}</h2>
            <p>{{asset.description}}</p>
            <p>{{asset.creation_date}}</p>
        </div>
    {% empty %}
        Oh no, empty!
    {% endfor %}
{% endblock %}

assets/templates/assets/login.html
{% extends 'main.html' %}

{% block title %}
    Login - {{ block.super }}
{% endblock title %}

{% block content %}
    <div class="container mx-auto px-6 lg:px-8 mt-8 text-center">
        <h1>Login</h1>
        <div class="bg-card-bg shadow-md rounded px-8 pt-6 pb-8 mb-4 flex flex-col md:w-1/2 xl:w-1/3 md:mx-auto">
            {% for field in form %}
                {% for error in field.errors %}
                    <p class="text-xs text-red-200">{{ error }}</p>
                {% endfor %}
            {% endfor %}
            {% for message in messages %}
					<p id="messages" class="font-semibold text-accent-yellow mb-4">{{message}}</p>
			{% endfor %}
            <form method="POST">
                {% csrf_token %}
                <div class="mb-4 text-left">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="username">
                    Username
                </label>
                <input name='username' class="shadow border rounded w-full py-2 px-3 text-gray-800" id="username" type="text" placeholder="Username">
                </div>
                <div class="mb-6 text-left">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="password1">
                    Password
                </label>
                <input name='password' class="shadow border rounded w-full py-2 px-3 text-gray-800" id="password" type="password" placeholder="Password">
                {% comment %} <p class="text-xs italic">Please choose a password.</p> {% endcomment %}
                </div>
                <div class="flex items-center justify-between">
                <button class="bg-white hover:bg-accent-yellow hover:text-black text-gray-700 font-bold py-2 px-4 rounded" type="submit">
                    Login
                </button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

assets/templates/assets/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/tailwind.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" />
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <title>DevLoot</title>
</head>

<body class="antialiased bg-page-bg text-white">
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    {% include 'assets/navbar.html' %}

    {% block content %}

    {% endblock %}
    
    {% include 'assets/footer.html' %}

</body>

</html>

assets/templates/assets/register.html
{% extends 'main.html' %}

{% block title %}
    Register - {{ block.super }}
{% endblock title %}

{% block content %}
    <div class="container mx-auto px-6 lg:px-8 mt-8 text-center">
        <h1>Register</h1>
        <div class="bg-card-bg shadow-md rounded px-8 pt-6 pb-8 mb-4 flex flex-col md:w-1/2 xl:w-1/3 md:mx-auto">
            {% for field in form %}
                {% for error in field.errors %}
                    <p class="text-xs text-red-200">{{ error }}</p>
                {% endfor %}
            {% endfor %}
            <form method="POST">
                {% csrf_token %}
                <div class="mb-4 text-left">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="username">
                    Username
                </label>
                {{ form.username }}
                <label class="block text-grey-darker text-sm font-bold mb-2" for="username">
                    Email
                </label>
                {{ form.email }}
                </div>
                <div class="mb-6 text-left">
                <label class="block text-grey-darker text-sm font-bold mb-2" for="password1">
                    Password
                </label>
                {{ form.password1 }}
                <label class="block text-grey-darker text-sm font-bold mb-2" for="password2">
                    Password Confirmation
                </label>
                {{ form.password2 }}
                {% comment %} <p class="text-xs italic">Please choose a password.</p> {% endcomment %}
                </div>
                <div class="flex items-center justify-between">
                <button class="bg-white hover:bg-accent-yellow hover:text-black text-gray-700 font-bold py-2 px-4 rounded" type="submit">
                    Register
                </button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

templates/navbar.html
<div class="w-full text-gray-200 bg-nav-bg">
    <div x-data="{ open: false }"
        class="flex flex-col container px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
        <div class="py-4 flex flex-row items-center justify-between">
            <a href="{% url 'assets:home' %}"
                class="text-lg font-semibold tracking-widest text-gray-200 uppercase rounded-lg focus:outline-none focus:shadow-outline">DevLoot</a>
            <button class="md:hidden rounded-lg focus:outline-none focus:shadow-outline" @click="open = !open">
                <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
                    <path x-show="!open" fill-rule="evenodd"
                        d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z"
                        clip-rule="evenodd"></path>
                    <path x-show="open" fill-rule="evenodd"
                        d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                        clip-rule="evenodd"></path>
                </svg>
            </button>
        </div>
        <nav :class="{'flex': open, 'hidden': !open}"
            class="flex-col flex-grow pb-4 md:pb-0 hidden md:flex md:justify-end md:flex-row">
            <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-accent-yellow focus:bg-gray-200 focus:outline-none focus:shadow-outline"
                href="{% url 'assets:home' %}">Browse</a>
            <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-accent-yellow focus:bg-gray-200 focus:outline-none focus:shadow-outline"
                href="{% url 'assets:featured' %}">Featured</a>
            <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-accent-yellow focus:bg-gray-200 focus:outline-none focus:shadow-outline"
                href="#">Contributor Packs</a>
            {% if user.is_authenticated %}
                <a class="px-2 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg md:mt-0 md:ml-2 hover:text-gray-900 focus:text-gray-900 hover:bg-accent-yellow focus:bg-gray-200 focus:outline-none focus:shadow-outline"
                        href="{% url 'assets:logout' %}">Logout</a>
            {% else %}
                <div class="mt-2 md:mt-0 md:ml-2">
                    <a class="px-2 py-2 text-sm font-semibold bg-transparent rounded-lg hover:text-gray-900 focus:text-gray-900 hover:bg-accent-yellow focus:bg-gray-200 focus:outline-none focus:shadow-outline"
                        href="{% url 'assets:login' %}">Login</a> | <a class="px-2 py-2 text-sm font-semibold bg-transparent rounded-lg hover:text-gray-900 focus:text-gray-900 hover:bg-accent-yellow focus:bg-gray-200 focus:outline-none focus:shadow-outline"
                        href="{% url 'assets:register' %}">Register</a>
                </div>
            {% endif %}
        </nav>
    </div>
    <div class="container px-4 mx-auto md:px-6 lg:px-8">
            <i class="fas fa-search absolute z-10 search-icon" aria-hidden="true"></i>
            <input class="w-full bg-card-bg outline-none h-10 text-white pl-10 mb-3 rounded-lg relative" type="text"
                name="search" id="search" />
    </div>
</div>